In [4]:
import pandas as pd

In [9]:
lst=[1,2,3,4]
s= pd.Series(lst)
s

0    1
1    2
2    3
3    4
dtype: int64

In [10]:
lst=[1,2,3,4]
s= pd.Series(lst,dtype=float)
s

0    1.0
1    2.0
2    3.0
3    4.0
dtype: float64

In [12]:
lst=[1,2,3,4]
s= pd.Series(lst,dtype=float, index=['A','B','C','D'])
s

A    1.0
B    2.0
C    3.0
D    4.0
dtype: float64

In [13]:
x= pd.Series(['Maha','Ayla'])
y= pd.Series(['Ethar','Layan'])
z=pd.concat([x,y])
z

0     Maha
1     Ayla
0    Ethar
1    Layan
dtype: str

In [14]:
x= pd.Series(['Maha','Ayla'])
y= pd.Series(['Ethar','Layan'])
z=pd.concat([x,y],ignore_index=True)
z

0     Maha
1     Ayla
2    Ethar
3    Layan
dtype: str

In [5]:
s=pd.Series ( {10:'A', 20:'B', 30:'C', 40:'D', 50:'B'} )
s

10    A
20    B
30    C
40    D
50    B
dtype: str

In [51]:
s.drop(30)

10    A
20    B
40    D
50    F
dtype: str

In [52]:
s.drop(30, inplace=True)
s

10    A
20    B
40    D
50    F
dtype: str

In [11]:
s.drop_duplicates(inplace=True)
s

10    A
20    B
30    C
40    D
dtype: str

In [14]:
x= pd.Series([1,2,3,4,5])
x

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [15]:
x=x.add(5)
x

0     6
1     7
2     8
3     9
4    10
dtype: int64

In [16]:
x=x.sub(5)
x

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [17]:
x=x.mul(5)
x

0     5
1    10
2    15
3    20
4    25
dtype: int64

In [18]:
x=x.div(5)
x

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

In [23]:
data ={
    'StudentName': ['Maha','Layan','Reham','Ayla'],
    'StudentGrade': ['A+','A','B+','B']
}
Students=pd.DataFrame(data)
Students

  StudentName StudentGrade
0        Maha           A+
1       Layan            A
2       Reham           B+
3        Ayla            B

In [28]:
#if we have a csv file and we want to read from it :
Students = pd.read_csv('Students.csv')
Students

  StudentName StudentGrade
0        Maha           A+
1       Layan            A
2       Reham           B+
3        Ayla            B

In [ ]:
#if we want to convert our dataframe to csv file:
Students.to_csv("Students.csv", index=False)

In [ ]:
#to show first n lines in dataframe:
Students.head(n)

In [ ]:
#to show the last n lines in dataframe:
Students.tail(n)

In [ ]:
#Using group by to sum a specific value in one colums and select aggregiation function (sum,mean,avg,max,min)
Students[['Major','GPA']].groupby('Level').mean()

In [ ]:
#to get discription about the data we obtain:
Students.describe(include=[object]) #اذا ما حطيت الانكلود بيطلع لي معلومات عن القيم الرقمية فقط

In [ ]:
# reaching data in a spicific column
Students['Name']
Students[['Name','Major']]

In [ ]:
# gitting to only n rows by index 
Students[3:6] # اذا عندي ١٠٠ صف ونبغى بس اول كم واحد

In [ ]:
#recovring data by index
Students.loc[1:5, ['Name','Major']]

In [ ]:
#gitting random data from dataframe
Students.sample(5,random_state=23)

In [ ]:
#gitting specific data that succed a condition
Student[Students['GPA']>4.50]

In [ ]:
#filtring missing value 
Students[Students['Level'].isnull()] #يرجع بس اللي فيها نول

In [ ]:
#Deleting Column(1):
Students.drop('Name', axis=1, inplace=True)

#Deleting row(0): 
Students.drop(5, axis=0, inplace=True)

In [ ]:
#droping null value:
Students.dropna(inplace=True)
Students.dropna(subset=["Level"], inplace=True)

#filling null value:
Students["GPA"].fillna(0, inplace=True)